"""changed havejob

Revision ID: 17436a790ddf
Revises: 6eb562ce92d5
Create Date: 2020-11-13 21:38:00.137649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17436a790ddf'
down_revision = '6eb562ce92d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('have_job_ibfk_1', 'have_job', type_='foreignkey')
    op.drop_column('have_job', 'profession_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('have_job', sa.Column('profession_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('have_job_ibfk_1', 'have_job', 'profession', ['profession_id'], ['id'])
    # ### end Alembic commands ###
