"""added number to joblesses

Revision ID: 26bc8ccd09cb
Revises: 46e560438b6b
Create Date: 2020-11-13 21:21:51.467151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26bc8ccd09cb'
down_revision = '46e560438b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobless', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobless', 'number')
    # ### end Alembic commands ###
