"""second-migration

Revision ID: 66f3abd3d843
Revises: 34499736469e
Create Date: 2020-11-13 20:33:13.580798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66f3abd3d843'
down_revision = '34499736469e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profession_ibfk_1', 'profession', type_='foreignkey')
    op.drop_column('profession', 'vacancy_id')
    op.add_column('vacancy', sa.Column('profession_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vacancy', 'profession', ['profession_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancy', type_='foreignkey')
    op.drop_column('vacancy', 'profession_id')
    op.add_column('profession', sa.Column('vacancy_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('profession_ibfk_1', 'profession', 'vacancy', ['vacancy_id'], ['id'])
    # ### end Alembic commands ###
