export const SectionsActionTypes = {
  SET_SECTIONS: 'SET_SECTIONS',
  SET_CURRENT_SECTION: 'SET_CURRENT_SECTION',
  SET_PROFESSIONS: 'SET_PROFESSIONS',
  RESET_SECTIONS_STATE: 'RESET_SECTIONS_STATE',
};
